branches:
  only:
    - master
language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew build
